@LabInsight.Api_HostAddress = http://localhost:5080

GET {{LabInsight.Api_HostAddress}}/api/getGraphItemData/1
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getLaboratories
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getAnalysisCategories
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getGraphTypes
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getGraphDataTypes
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getAnalyses?page=1&pageSize=50
Accept: application/json

###

POST {{LabInsight.Api_HostAddress}}/api/upsertGraphItem
Content-Type: application/json

{
  "name": "Monthly Analysis Volume",
  "description": "Monthly volume for Frankfurt",
  "graphTypeId": 2,
  "graphDataTypeId": 1,
  "content": "{\"filters\":{\"laboratoryId\":1},\"groupBy\":\"MONTH\"}"
}

###

POST {{LabInsight.Api_HostAddress}}/api/upsertGraphItem
Content-Type: application/json

{
  "id": 1,
  "name": "Monthly Analysis Volume",
  "description": "Updated description",
  "graphTypeId": 2,
  "graphDataTypeId": 1,
  "content": "{\"filters\":{\"laboratoryId\":1},\"groupBy\":\"MONTH\"}"
}
