@LabInsight.Api_HostAddress = http://localhost:5080

GET {{LabInsight.Api_HostAddress}}/api/getGraphItemData/1?isDeleted=false
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getLaboratories?isDeleted=false
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getAnalysisCategories?isDeleted=false
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getGraphTypes?isDeleted=false
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getGraphDataTypes?isDeleted=false
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getAnalyses?page=1&pageSize=50&isDeleted=false
Accept: application/json

###

GET {{LabInsight.Api_HostAddress}}/api/getGraphItems?isDeleted=false
Accept: application/json

###

POST {{LabInsight.Api_HostAddress}}/api/upsertGraphItem
Content-Type: application/json

{
  "name": "Monthly Analysis Volume",
  "description": "Monthly volume for Frankfurt",
  "graphTypeId": 2,
  "graphDataTypeId": 1,
  "content": "{\"filters\":{\"laboratoryId\":1},\"groupBy\":\"MONTH\"}"
}

###

POST {{LabInsight.Api_HostAddress}}/api/upsertGraphItem
Content-Type: application/json

{
  "id": 1,
  "name": "Monthly Analysis Volume",
  "description": "Updated description",
  "graphTypeId": 2,
  "graphDataTypeId": 1,
  "content": "{\"filters\":{\"laboratoryId\":1},\"groupBy\":\"MONTH\"}"
}

###

DELETE {{LabInsight.Api_HostAddress}}/api/deleteGraphItem/1

###

POST {{LabInsight.Api_HostAddress}}/api/updateGraphOrdering
Content-Type: application/json

[
  { "graphId": 1, "ordering": 1 },
  { "graphId": 2, "ordering": 2 }
]
