// <auto-generated />
using System;
using LabInsight.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabInsight.Api.Migrations
{
    [DbContext(typeof(LabInsightDbContext))]
    partial class LabInsightDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabInsight.Api.Entities.AnalysisCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ExpectedProcessingHours")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("analysis_categories", (string)null);
                });

            modelBuilder.Entity("LabInsight.Api.Entities.MetricDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TechnicalName")
                        .IsUnique();

                    b.ToTable("metric_definitions", (string)null);
                });

            modelBuilder.Entity("LabInsight.Api.Entities.DashboardWidgetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MetricDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("VisualizationTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Ordering")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetricDefinitionId");

                    b.HasIndex("VisualizationTypeId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Ordering");

                    b.ToTable("dashboard_widgets", (string)null);
                });

            modelBuilder.Entity("LabInsight.Api.Entities.VisualizationTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TechnicalName")
                        .IsUnique();

                    b.ToTable("visualization_types", (string)null);
                });

            modelBuilder.Entity("LabInsight.Api.Entities.LabAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("AnalysisNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisCategoryId");

                    b.HasIndex("AnalysisNumber")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LaboratoryId");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("Status");

                    b.ToTable("lab_analyses", (string)null);
                });

            modelBuilder.Entity("LabInsight.Api.Entities.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("laboratories", (string)null);
                });

            modelBuilder.Entity("LabInsight.Api.Entities.DashboardWidgetEntity", b =>
                {
                    b.HasOne("LabInsight.Api.Entities.MetricDefinitionEntity", "MetricDefinition")
                        .WithMany("DashboardWidgets")
                        .HasForeignKey("MetricDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabInsight.Api.Entities.VisualizationTypeEntity", "VisualizationType")
                        .WithMany("DashboardWidgets")
                        .HasForeignKey("VisualizationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetricDefinition");

                    b.Navigation("VisualizationType");
                });

            modelBuilder.Entity("LabInsight.Api.Entities.LabAnalysis", b =>
                {
                    b.HasOne("LabInsight.Api.Entities.AnalysisCategory", "AnalysisCategory")
                        .WithMany("Analyses")
                        .HasForeignKey("AnalysisCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LabInsight.Api.Entities.Laboratory", "Laboratory")
                        .WithMany("Analyses")
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnalysisCategory");

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("LabInsight.Api.Entities.AnalysisCategory", b =>
                {
                    b.Navigation("Analyses");
                });

            modelBuilder.Entity("LabInsight.Api.Entities.MetricDefinitionEntity", b =>
                {
                    b.Navigation("DashboardWidgets");
                });

            modelBuilder.Entity("LabInsight.Api.Entities.VisualizationTypeEntity", b =>
                {
                    b.Navigation("DashboardWidgets");
                });

            modelBuilder.Entity("LabInsight.Api.Entities.Laboratory", b =>
                {
                    b.Navigation("Analyses");
                });
#pragma warning restore 612, 618
        }
    }
}
