import {
  GRAPH_DATA_TYPE_TECHNICAL_NAMES,
  GraphDataTypeTechnicalName
} from '../models/graph-data-type-technical-name';
import {
  GRAPH_TYPE_TECHNICAL_NAMES,
  GraphTypeTechnicalName
} from '../models/graph-type-technical-name';

export const GRAPH_DATA_TYPE_ALLOWED_GRAPH_TYPES: Record<
  GraphDataTypeTechnicalName,
  readonly GraphTypeTechnicalName[]
> = {
  [GRAPH_DATA_TYPE_TECHNICAL_NAMES.ANALYSIS_VOLUME]: [
    GRAPH_TYPE_TECHNICAL_NAMES.LINE_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.BAR_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [GRAPH_DATA_TYPE_TECHNICAL_NAMES.ANALYSIS_STATUS]: [
    GRAPH_TYPE_TECHNICAL_NAMES.DOUGHNUT_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.PIE_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.BAR_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [GRAPH_DATA_TYPE_TECHNICAL_NAMES.PROCESSING_TIME]: [
    GRAPH_TYPE_TECHNICAL_NAMES.BAR_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.LINE_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [GRAPH_DATA_TYPE_TECHNICAL_NAMES.ANALYSIS_CATEGORY]: [
    GRAPH_TYPE_TECHNICAL_NAMES.DOUGHNUT_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.PIE_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.BAR_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [GRAPH_DATA_TYPE_TECHNICAL_NAMES.LABORATORY_WORKLOAD]: [
    GRAPH_TYPE_TECHNICAL_NAMES.BAR_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [GRAPH_DATA_TYPE_TECHNICAL_NAMES.PRIORITY_DISTRIBUTION]: [
    GRAPH_TYPE_TECHNICAL_NAMES.DOUGHNUT_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.PIE_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.BAR_CHART
  ],
  [GRAPH_DATA_TYPE_TECHNICAL_NAMES.COMPLETION_RATE]: [
    GRAPH_TYPE_TECHNICAL_NAMES.DOUGHNUT_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.BAR_CHART
  ],
  [GRAPH_DATA_TYPE_TECHNICAL_NAMES.DELAYED_ANALYSES]: [
    GRAPH_TYPE_TECHNICAL_NAMES.BAR_CHART,
    GRAPH_TYPE_TECHNICAL_NAMES.DATA_GRID
  ]
};

export function getAllowedGraphTypes(
  graphDataType: GraphDataTypeTechnicalName
): readonly GraphTypeTechnicalName[] {
  return GRAPH_DATA_TYPE_ALLOWED_GRAPH_TYPES[graphDataType];
}

export function isGraphTypeAllowed(
  graphDataType: GraphDataTypeTechnicalName,
  graphType: GraphTypeTechnicalName
): boolean {
  return getAllowedGraphTypes(graphDataType).includes(graphType);
}
