import {
  METRIC_DEFINITION_TECHNICAL_NAMES,
  MetricDefinitionTechnicalName
} from '../models/metric-definition-technical-name';
import {
  VISUALIZATION_TYPE_TECHNICAL_NAMES,
  VisualizationTypeTechnicalName
} from '../models/visualization-type-technical-name';

export const METRIC_DEFINITION_ALLOWED_VISUALIZATION_TYPES: Record<
  MetricDefinitionTechnicalName,
  readonly VisualizationTypeTechnicalName[]
> = {
  [METRIC_DEFINITION_TECHNICAL_NAMES.ANALYSIS_VOLUME]: [
    VISUALIZATION_TYPE_TECHNICAL_NAMES.LINE_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.BAR_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [METRIC_DEFINITION_TECHNICAL_NAMES.ANALYSIS_STATUS]: [
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DOUGHNUT_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.PIE_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.BAR_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [METRIC_DEFINITION_TECHNICAL_NAMES.PROCESSING_TIME]: [
    VISUALIZATION_TYPE_TECHNICAL_NAMES.BAR_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.LINE_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [METRIC_DEFINITION_TECHNICAL_NAMES.ANALYSIS_CATEGORY]: [
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DOUGHNUT_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.PIE_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.BAR_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [METRIC_DEFINITION_TECHNICAL_NAMES.LABORATORY_WORKLOAD]: [
    VISUALIZATION_TYPE_TECHNICAL_NAMES.BAR_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DATA_GRID
  ],
  [METRIC_DEFINITION_TECHNICAL_NAMES.PRIORITY_DISTRIBUTION]: [
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DOUGHNUT_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.PIE_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.BAR_CHART
  ],
  [METRIC_DEFINITION_TECHNICAL_NAMES.COMPLETION_RATE]: [
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DOUGHNUT_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.BAR_CHART
  ],
  [METRIC_DEFINITION_TECHNICAL_NAMES.DELAYED_ANALYSES]: [
    VISUALIZATION_TYPE_TECHNICAL_NAMES.BAR_CHART,
    VISUALIZATION_TYPE_TECHNICAL_NAMES.DATA_GRID
  ]
};

export function getAllowedVisualizationTypes(
  metricDefinition: MetricDefinitionTechnicalName
): readonly VisualizationTypeTechnicalName[] {
  return METRIC_DEFINITION_ALLOWED_VISUALIZATION_TYPES[metricDefinition];
}

export function isVisualizationTypeAllowed(
  metricDefinition: MetricDefinitionTechnicalName,
  visualizationType: VisualizationTypeTechnicalName
): boolean {
  return getAllowedVisualizationTypes(metricDefinition).includes(visualizationType);
}
