export const GRAPH_DATA_TYPE_TECHNICAL_NAMES = {
  ANALYSIS_VOLUME: 'ANALYSIS_VOLUME',
  ANALYSIS_STATUS: 'ANALYSIS_STATUS',
  PROCESSING_TIME: 'PROCESSING_TIME',
  ANALYSIS_CATEGORY: 'ANALYSIS_CATEGORY',
  LABORATORY_WORKLOAD: 'LABORATORY_WORKLOAD',
  PRIORITY_DISTRIBUTION: 'PRIORITY_DISTRIBUTION',
  COMPLETION_RATE: 'COMPLETION_RATE',
  DELAYED_ANALYSES: 'DELAYED_ANALYSES'
} as const;

export type GraphDataTypeTechnicalName =
  (typeof GRAPH_DATA_TYPE_TECHNICAL_NAMES)[keyof typeof GRAPH_DATA_TYPE_TECHNICAL_NAMES];

const GRAPH_DATA_TYPE_TECHNICAL_NAME_SET = new Set<string>(
  Object.values(GRAPH_DATA_TYPE_TECHNICAL_NAMES)
);

export function isGraphDataTypeTechnicalName(
  value: string
): value is GraphDataTypeTechnicalName {
  return GRAPH_DATA_TYPE_TECHNICAL_NAME_SET.has(value);
}
