export const METRIC_DEFINITION_TECHNICAL_NAMES = {
  ANALYSIS_VOLUME: 'ANALYSIS_VOLUME',
  ANALYSIS_STATUS: 'ANALYSIS_STATUS',
  PROCESSING_TIME: 'PROCESSING_TIME',
  ANALYSIS_CATEGORY: 'ANALYSIS_CATEGORY',
  LABORATORY_WORKLOAD: 'LABORATORY_WORKLOAD',
  PRIORITY_DISTRIBUTION: 'PRIORITY_DISTRIBUTION',
  COMPLETION_RATE: 'COMPLETION_RATE',
  DELAYED_ANALYSES: 'DELAYED_ANALYSES'
} as const;

export type MetricDefinitionTechnicalName =
  (typeof METRIC_DEFINITION_TECHNICAL_NAMES)[keyof typeof METRIC_DEFINITION_TECHNICAL_NAMES];

const METRIC_DEFINITION_TECHNICAL_NAME_SET = new Set<string>(
  Object.values(METRIC_DEFINITION_TECHNICAL_NAMES)
);

export function isMetricDefinitionTechnicalName(
  value: string
): value is MetricDefinitionTechnicalName {
  return METRIC_DEFINITION_TECHNICAL_NAME_SET.has(value);
}
